CREATE TABLE global_category_rules (
    id              BIGSERIAL PRIMARY KEY ,
    keyword         VARCHAR(255) NOT NULL UNIQUE ,
    category_name   VARCHAR(100) NOT NULL ,
    created_at      TIMESTAMP NOT NULL DEFAULT NOW()
);

INSERT INTO global_category_rules (keyword, category_name) VALUES
--     GROCERIES
   ('rewe', 'Groceries'),
   ('edeka', 'Groceries'),
   ('aldi', 'Groceries'),
   ('lidl', 'Groceries'),
   ('kaufland', 'Groceries'),
   ('penny', 'Groceries'),
   ('netto', 'Groceries'),
   ('tegut', 'Groceries'),
   ('alnatura', 'Groceries'),
   ('rossmann', 'Groceries'),
   ('dm markt', 'Groceries'),
--    RESTAURANT
   ('backfactory', 'Restaurants'),
   ('backwerk', 'Restaurants'),
   ('mcdonalds', 'Restaurants'),
   ('burger king', 'Restaurants'),
   ('subway', 'Restaurants'),
   ('lieferando', 'Restaurants'),
   ('wolt', 'Restaurants'),
   ('starbucks', 'Restaurants'),
   ('nordsee', 'Restaurants'),
   ('vapiano', 'Restaurants'),
   ('restaurant', 'Restaurants'),
   ('cafe', 'Restaurants'),
   ('pizzeria', 'Restaurants'),
   ('kebab', 'Restaurants'),
   ('yormas', 'Restaurants'),
--    TRANSPORT
   ('deutsche bahn', 'Transport'),
   ('db bahn', 'Transport'),
   ('flixbus', 'Transport'),
   ('uber', 'Transport'),
   ('bolt', 'Transport'),
   ('free now', 'Transport'),
   ('bvg', 'Transport'),
   ('mvg', 'Transport'),
   ('hvv', 'Transport'),
   ('rmv', 'Transport'),
   ('vrn', 'Transport'),
   ('rnv', 'Transport'),
   ('ryanair', 'Transport'),
   ('lufthansa', 'Transport'),
   ('eurowings', 'Transport'),
   ('easyjet', 'Transport'),
   ('shell', 'Transport'),
   ('aral', 'Transport'),
   ('tankstelle', 'Transport'),
   ('adac', 'Transport'),
--    SUBSCRIPTION
   ('spotify', 'Subscriptions'),
   ('netflix', 'Subscriptions'),
   ('amazon prime', 'Subscriptions'),
   ('disney', 'Subscriptions'),
   ('dazn', 'Subscriptions'),
   ('microsoft', 'Subscriptions'),
   ('adobe', 'Subscriptions'),
   ('github', 'Subscriptions'),
   ('chatgpt', 'Subscriptions'),
   ('openai', 'Subscriptions'),
   ('notion', 'Subscriptions'),
   ('audible', 'Subscriptions'),
   ('telefonica', 'Subscriptions'),
   ('telekom', 'Subscriptions'),
   ('vodafone', 'Subscriptions'),
   ('o2', 'Subscriptions'),
--    HEALTH
   ('techniker krankenkasse', 'Health'),
   ('barmer', 'Health'),
   ('aok', 'Health'),
   ('dak', 'Health'),
   ('bkk', 'Health'),
   ('hek', 'Health'),
   ('knappschaft', 'Health'),
   ('debeka', 'Health'),
   ('apotheke', 'Health'),
   ('zahnarzt', 'Health'),
   ('krankenhaus', 'Health'),
   ('klinik', 'Health'),
--    SHOPPING
   ('amazon', 'Shopping'),
   ('zalando', 'Shopping'),
   ('zara', 'Shopping'),
   ('h&m', 'Shopping'),
   ('primark', 'Shopping'),
   ('about you', 'Shopping'),
   ('otto', 'Shopping'),
   ('saturn', 'Shopping'),
   ('mediamarkt', 'Shopping'),
   ('ikea', 'Shopping'),
   ('ebay', 'Shopping'),
   ('muji', 'Shopping'),
   ('deichmann', 'Shopping'),
   ('snipes', 'Shopping'),
--    RENT AND UTILITIES
   ('miete', 'Rent & Utilities'),
   ('bauverein', 'Rent & Utilities'),
   ('vonovia', 'Rent & Utilities'),
   ('deutsche wohnen', 'Rent & Utilities'),
   ('vattenfall', 'Rent & Utilities'),
   ('eon', 'Rent & Utilities'),
   ('rwe', 'Rent & Utilities'),
   ('mainova', 'Rent & Utilities'),
   ('stadtwerke', 'Rent & Utilities'),
   ('wasserwerke', 'Rent & Utilities'),
--    ENTERTAINMENT
   ('cinemaxx', 'Entertainment'),
   ('cinestar', 'Entertainment'),
   ('steam', 'Entertainment'),
   ('eventim', 'Entertainment'),
   ('ticketmaster', 'Entertainment'),
   ('mcfit', 'Entertainment'),
   ('clever fit', 'Entertainment'),
   ('jumpers', 'Entertainment'),
   ('lotterie', 'Entertainment'),
   ('fitness', 'Entertainment'),
--    DONATIONS
   ('unicef', 'Donations'),
   ('sos kinderdorf', 'Donations'),
   ('rotes kreuz', 'Donations'),
   ('greenpeace', 'Donations'),
   ('wwf', 'Donations'),
   ('caritas', 'Donations'),
   ('spende', 'Donations'),
--    UNIVERSITY
   ('studierendenwerk', 'University'),
   ('studentenwerk', 'University'),
   ('mensa', 'University'),
   ('semesterbeitrag', 'University'),
   ('hochschule', 'University'),
   ('fachhochschule', 'University'),
   ('tu darmstadt', 'University'),
   ('tu berlin', 'University'),
   ('tu münchen', 'University'),
   ('rwth', 'University'),
   ('tu dresden', 'University'),
   ('kit karlsruhe', 'University'),
--    TRANSFERS
   ('revolut', 'Transfers'),
   ('wise', 'Transfers'),
   ('paypal', 'Transfers'),
   ('überweisung', 'Transfers'),
   ('dauerauftrag', 'Transfers'),
   ('Echtzeitüberweisung', 'Transfers');